# Task 1.1

In [63]:

n = int(input("Nhập vào số nguyên n: "))
list_Number = []
i = 0
while i < n:
  x = int(input("Nhập vào giá trị x" + str(i + 1) + ": "))
  list_Number.append(x)
  i += 1
print("Giá trị lớn nhất là: ", max(list_Number))
print("Giá trị nhỏ nhất là: ", min(list_Number))
print("Tổng là: " + str(sum(list_Number)))
list_Number.sort()
print(list_Number)
duong = 0
am = 0
for i in list_Number:
  if i > 0:
    duong += 1
  elif i < 0:
    am += 1
print("Danh sách có ", str(duong) , "số dương")
print("Danh sách có ", str(am) , "số âm")

Nhập vào số nguyên n: 3
Nhập vào giá trị x1: 1
Nhập vào giá trị x2: 4
Nhập vào giá trị x3: 3
Giá trị lớn nhất là:  4
Giá trị nhỏ nhất là:  1
Tổng là: 8
[1, 3, 4]
Danh sách có  3 số dương
Danh sách có  0 số âm


# Task 1.2

In [30]:

def compute_S(n):
  result = 0
  temp = 1
  for i in range(1, n + 1):
    temp *= i
    result += temp
  return result


In [31]:
compute_S(4)

33

# Task 1.3

In [34]:

# from ctypes import c_void_p
# class Account:
#   def __init__(self, name, email, country, ):

# class Post:
#   def__init__(self, content, subject, likes):
#     self.__content = content
#     self.__subject = subject
#     self.__likes = likes

In [35]:
# p = Post("aaa", "ML", 100)
# print(p)

# Task 2.1

In [48]:
import numpy as np
# Tạo mảng
arr = np.arange(10,26)
print(arr)
# Đảo mảng
reverse_arr = arr[::-1]
print(reverse_arr)



[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]
[25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


# Task 2.2

In [52]:
# Task 2.2. Develop a NumPy program that constructs an array by repeating.
# Input: [1, 2, 3, 4]

arr = np.arange(1, 5)
print(arr)
arr_double = np.tile(arr, 2)
print(arr_double)
arr_triple = np.tile(arr, 3)
print(arr_triple)

[1 2 3 4]
[1 2 3 4 1 2 3 4]
[1 2 3 4 1 2 3 4 1 2 3 4]


# Task 2.3

In [62]:
# Task 2.3. Develop a NumPy program to replace all elements of the NumPy array that are less than a specified value by this specified value.
# # Original array
arr = np.array([(0.42, 0.48, 0.32), (0.74, 0.58, 0.38), (0.51, 0.34, 0.15)])
print(arr)
print()
print(arr[arr > 0.5])
# Replace all elements of the original array with .5 for values which are greater than .5
arr[arr > 0.5] = 0.5
print()
print(arr)

[[0.42 0.48 0.32]
 [0.74 0.58 0.38]
 [0.51 0.34 0.15]]

[0.74 0.58 0.51]

[[0.42 0.48 0.32]
 [0.5  0.5  0.38]
 [0.5  0.34 0.15]]
